version: "3.9"

services:
  db:
    image: pgvector/pgvector:pg16   # Postgres 16 with pgvector
    container_name: resume_pg
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: resume_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
